### ISSUE TITLE
Issues with df output: extra rows and 1970 timestamp

### ISSUE THREAD

**Issue by Robinlovelace** [petermeissner/ical#2] opened 2019-02-18 08:09 UTC
Great work on this! Was looking at importing it as a back-end to create `ical` objects in the `calendar` package, but it seems that it's producing unexpected results.
Please try to reproduce the following reprex, for example, in which I think you package creates unnecessary rows at the beginning, and gets the `last.modified` dates wrong (there are also columns missing from `c2` but that may be by design):

``` r
u = "https://github.com/ATFutures/calendar/releases/download/0.0.1/d-mini.ics"
download.file(url = u, destfile = "d-mini.ics")
c1 = calendar::ic_read("d-mini.ics")
ncol(c1)
#> [1] 26
nrow(c1)
#> [1] 21
head(c1)
#> # A tibble: 6 x 26
#>   DESCRIPTION UID   SUMMARY `DTSTART;TZID=G… `DTEND;TZID=GMT… CLASS
#>   <chr>       <chr> <chr>   <chr>            <chr>            <chr>
#> 1 "Heads-up:… "040… Meet-u… 20181119T110000  20181119T113000  PUBL…
#> 2 "COlin - R… "040… R mark… 20181120T090000  20181120T110000  PUBL…
#> 3 "\\n"       "040… Send t… 20181120T090000  20181120T093000  PUBL…
#> 4 "1 week be… "040… CDAS c… 20181120T150000  20181120T160000  PUBL…
#> 5 "Navigatin… "040… "ITS R… 20181121T140000  20181121T150000  PUBL…
#> 6 "The meeti… "040… [Envne… <NA>             <NA>             PUBL…
#> # … with 20 more variables: PRIORITY <chr>, DTSTAMP <chr>, TRANSP <chr>,
#> #   STATUS <chr>, SEQUENCE <chr>, LOCATION <chr>,
#> #   `X-MICROSOFT-CDO-APPT-SEQUENCE` <chr>,
#> #   `X-MICROSOFT-CDO-BUSYSTATUS` <chr>,
#> #   `X-MICROSOFT-CDO-INTENDEDSTATUS` <chr>,
#> #   `X-MICROSOFT-CDO-ALLDAYEVENT` <chr>,
#> #   `X-MICROSOFT-CDO-IMPORTANCE` <chr>, `X-MICROSOFT-CDO-INSTTYPE` <chr>,
#> #   `X-MICROSOFT-DONOTFORWARDMEETING` <chr>,
#> #   `X-MICROSOFT-DISALLOW-COUNTER` <chr>, `DTSTART;TZID=Greenwich Standard
#> #   Time` <chr>, `DTEND;TZID=Greenwich Standard Time` <chr>,
#> #   `DTSTART;VALUE=DATE` <date>, `DTEND;VALUE=DATE` <date>,
#> #   `DTSTART;TZID=Romance Standard Time` <chr>, `DTEND;TZID=Romance
#> #   Standard Time` <chr>
c2 = ical::ical_parse_df("d-mini.ics")
ncol(c2)
#> [1] 7
nrow(c2)
#> [1] 25
head(c2)
#>                                                                                                                uid
#> 1                                                                                                             <NA>
#> 2                                                                                                             <NA>
#> 3                                                                                                             <NA>
#> 4                                                                                                             <NA>
#> 5 040000008200E00074C5B7101A82E00800000000A422E1FB9167D401000000000000000010000000A5A5A9C201712E4686F3BEF8AA455230
#> 6 040000008200E00074C5B7101A82E00800000000EB39A1D82871D4010000000000000000100000002991E11530BAE14398A3E231D58C870F
#>                             summary               start
#> 1                              <NA> 1970-01-01 01:00:00
#> 2                              <NA> 1970-01-01 01:00:00
#> 3                              <NA> 1970-01-01 01:00:00
#> 4                              <NA> 1970-01-01 01:00:00
#> 5 Meet-up re global health projects 2018-11-19 11:00:00
#> 6      R markup training with Robin 2018-11-20 09:00:00
#>                   end
#> 1 1970-01-01 01:00:00
#> 2 1970-01-01 01:00:00
#> 3 1970-01-01 01:00:00
#> 4 1970-01-01 01:00:00
#> 5 2018-11-19 11:30:00
#> 6 2018-11-20 11:00:00
#>                                                                                                                                   description
#> 1                                                                                                                                        <NA>
#> 2                                                                                                                                        <NA>
#> 3                                                                                                                                        <NA>
#> 4                                                                                                                                        <NA>
#> 5 Heads-up: this will be a 3 way meeting now, to include Stephen Turrell from Leeds City Council, on the 9th floor of the Worsley Building.\n
#> 6              COlin - Robin has agreed to do a training session for me and Roger on R Markup at this date and time if you want to join us.\n
#>         last.modified    status
#> 1 1970-01-01 01:00:00      <NA>
#> 2 1970-01-01 01:00:00      <NA>
#> 3 1970-01-01 01:00:00      <NA>
#> 4 1970-01-01 01:00:00      <NA>
#> 5 1970-01-01 01:00:00 CONFIRMED
#> 6 1970-01-01 01:00:00 CONFIRMED
```

<sup>Created on 2019-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.5.2 (2018-12-20)
#>  os       Ubuntu 18.04.2 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language en_GB:en                    
#>  collate  en_GB.UTF-8                 
#>  ctype    en_GB.UTF-8                 
#>  tz       Europe/London               
#>  date     2019-02-18                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       lib
#>  assertthat    0.2.0      2017-04-11 [3]
#>  backports     1.1.3      2018-12-14 [3]
#>  calendar      0.0.1      2019-02-05 [1]
#>  callr         3.1.1      2018-12-21 [3]
#>  cli           1.0.1      2018-09-25 [1]
#>  crayon        1.3.4      2017-09-16 [3]
#>  curl          3.3        2019-01-10 [1]
#>  desc          1.2.0      2018-05-01 [3]
#>  devtools      2.0.1      2018-10-26 [1]
#>  digest        0.6.18     2018-10-10 [3]
#>  evaluate      0.12       2018-10-09 [3]
#>  fansi         0.4.0      2018-10-05 [3]
#>  fs            1.2.6      2018-08-23 [1]
#>  glue          1.3.0.9000 2019-01-28 [1]
#>  highr         0.7        2018-06-09 [3]
#>  htmltools     0.3.6      2017-04-28 [3]
#>  ical          0.1.6      2019-01-21 [1]
#>  jsonlite      1.6        2018-12-07 [1]
#>  knitr         1.21       2018-12-10 [3]
#>  magrittr      1.5        2014-11-22 [3]
#>  memoise       1.1.0      2017-04-21 [3]
#>  pillar        1.3.1      2018-12-15 [1]
#>  pkgbuild      1.0.2      2018-10-16 [3]
#>  pkgconfig     2.0.2      2018-08-16 [3]
#>  pkgload       1.0.2      2018-10-29 [3]
#>  prettyunits   1.0.2      2015-07-13 [1]
#>  processx      3.2.1      2018-12-05 [3]
#>  ps            1.3.0      2018-12-21 [3]
#>  R6            2.4.0      2019-02-14 [1]
#>  Rcpp          1.0.0      2018-11-07 [1]
#>  remotes       2.0.2      2018-10-30 [1]
#>  rlang         0.3.1      2019-01-08 [1]
#>  rmarkdown     1.11       2018-12-08 [1]
#>  rprojroot     1.3-2      2018-01-03 [1]
#>  sessioninfo   1.1.1      2018-11-05 [1]
#>  stringi       1.2.4      2018-07-20 [3]
#>  stringr       1.4.0      2019-02-10 [1]
#>  testthat      2.0.1      2018-10-13 [1]
#>  tibble        2.0.1      2019-01-12 [1]
#>  usethis       1.4.0      2018-08-14 [1]
#>  utf8          1.1.4      2018-05-24 [3]
#>  V8            2.0        2019-02-07 [1]
#>  withr         2.1.2      2018-03-15 [3]
#>  xfun          0.4        2018-10-23 [1]
#>  yaml          2.2.0      2018-07-25 [3]
#>  source                             
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.1)                     
#>  Github (ATFutures/calendar@6c67c0f)
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  Github (tidyverse/glue@8188cea)    
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.2)                     
#>  CRAN (R 3.5.0)                     
#>  CRAN (R 3.5.1)                     
#>  CRAN (R 3.5.1)                     
#> 
#> [1] /home/robin/R/x86_64-pc-linux-gnu-library/3.5
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

There are issues with the `calendar` parser also, hence looking for an alternative back-end...

**Comment by petermeissner** [comment] 2019-07-14 19:55
I can confirm that something funny is going on ... this needs further inspection. 

I try looking into this, this week.

**Comment by petermeissner** [comment] 2019-07-17 18:59
Update on too many rows:

For whatever reason I think the parser is picking up those 4 VTIMEZONE entries at the start of the calendar - why, I yet do not know. So it's not completely random but its off.

**Comment by petermeissner** [comment] 2019-07-17 19:14
Update on strange timestamps: 

All those last.modified timestamps are missing in the example calendar but missing timestamps are obviously not handled correctly but instead lead t returning the POSIX epoch start timestamp for second 0 which is the 1970-01-01.

**Comment by petermeissner** [comment] 2019-07-17 19:16
... its all not too hard to get right. I will fix it the next days.

**Comment by Robinlovelace** [comment] 2019-07-28 08:32
Thanks for the update. Will be good to have a unified `.ics` reader for R. Imagine the issue is on the R side because [ical.js](https://github.com/mozilla-comm/ical.js) seems solid.

**Comment by petermeissner** [comment] 2019-08-16 07:37
Agreed. And working on that ... should be not to much work so chances are good to pull this off as a side project within the next 2 months. 

In regard to the empty lines: 

They are actually there in the data. Those are entries of type VTIMEZONE. Since I simply loop over all entries those get picked up and put in the resulting data.frame. But since they do not have any of the entries I extract for VEVENTs they seem empty except for the buggy dates. 

- I will make getting anything but VEVENT entries optional.
- I will fix the date issue - missings shall be missings and not some valid date in the past.

**Comment by petermeissner** [comment] 2019-08-18 18:23
fixed with:

- 7b1e17a6b3e8f58a5c962d38e676d480dc377056
- 7cf417ce360391e8fe726d23b198a942bcd10faf

**Closed as completed by petermeissner** 2019-08-18 18:23 UTC
Labels: bug

**Comment by Robinlovelace** [comment] 2019-09-09 06:58
Great work @petermeissner, do you think `ical` would make a good back-end for `calendar`? Read/write functionality would be great but just read would be useful.

**Comment by petermeissner** [comment] 2019-09-09 08:02
Hey, might be. Could you give me some use cases / examples for writing than
I can give it a try see how things work out.

Reading, should be a solved problem now. I now read all fields and filter
out meta stuff - with the option to keep everything.

Robin <notifications@github.com> schrieb am Mo., 9. Sep. 2019, 08:58:

**Comment by Robinlovelace** [comment] 2019-09-09 08:43
Confirmed, the datetime issue is now fixed. Interesting that `ical` generates fewer columns:

``` r
devtools::install_github("petermeissner/ical")
#> Skipping install of 'ical' from a github remote, the SHA1 (35f7d747) has not changed since last install.
#>   Use `force = TRUE` to force installation
    install.packages("calendar")
#> package 'calendar' successfully unpacked and MD5 sums checked
#> 
#> The downloaded binary packages are in
#>  C:\Users\georl\AppData\Local\Temp\Rtmp6PaiIC\downloaded_packages
    
    u = "https://github.com/ATFutures/calendar/releases/download/0.0.1/d-mini.ics"
    download.file(url = u, destfile = "d-mini.ics")
    c1 = calendar::ic_read("d-mini.ics")
    ncol(c1)
#> [1] 26
    nrow(c1)
#> [1] 21
    head(c1)
#> # A tibble: 6 x 26
#>   DESCRIPTION UID   SUMMARY `DTSTART;TZID=G~ `DTEND;TZID=GMT~ CLASS
#>   <chr>       <chr> <chr>   <chr>            <chr>            <chr>
#> 1 "Heads-up:~ "040~ Meet-u~ 20181119T110000  20181119T113000  PUBL~
#> 2 "COlin - R~ "040~ R mark~ 20181120T090000  20181120T110000  PUBL~
#> 3 "\\n"       "040~ Send t~ 20181120T090000  20181120T093000  PUBL~
#> 4 "1 week be~ "040~ CDAS c~ 20181120T150000  20181120T160000  PUBL~
#> 5 "Navigatin~ "040~ "ITS R~ 20181121T140000  20181121T150000  PUBL~
#> 6 "The meeti~ "040~ [Envne~ <NA>             <NA>             PUBL~
#> # ... with 20 more variables: PRIORITY <chr>, DTSTAMP <chr>, TRANSP <chr>,
#> #   STATUS <chr>, SEQUENCE <chr>, LOCATION <chr>,
#> #   `X-MICROSOFT-CDO-APPT-SEQUENCE` <chr>,
#> #   `X-MICROSOFT-CDO-BUSYSTATUS` <chr>,
#> #   `X-MICROSOFT-CDO-INTENDEDSTATUS` <chr>,
#> #   `X-MICROSOFT-CDO-ALLDAYEVENT` <chr>,
#> #   `X-MICROSOFT-CDO-IMPORTANCE` <chr>, `X-MICROSOFT-CDO-INSTTYPE` <chr>,
#> #   `X-MICROSOFT-DONOTFORWARDMEETING` <chr>,
#> #   `X-MICROSOFT-DISALLOW-COUNTER` <chr>, `DTSTART;TZID=Greenwich Standard
#> #   Time` <chr>, `DTEND;TZID=Greenwich Standard Time` <chr>,
#> #   `DTSTART;VALUE=DATE` <date>, `DTEND;VALUE=DATE` <date>,
#> #   `DTSTART;TZID=Romance Standard Time` <chr>, `DTEND;TZID=Romance
#> #   Standard Time` <chr>
    c2 = ical::ical_parse_df("d-mini.ics")
    ncol(c2)
#> [1] 12
    nrow(c2)
#> [1] 21
    head(c2)
#>                                                                                                                uid
#> 1 040000008200E00074C5B7101A82E00800000000A422E1FB9167D401000000000000000010000000A5A5A9C201712E4686F3BEF8AA455230
#> 2 040000008200E00074C5B7101A82E00800000000EB39A1D82871D4010000000000000000100000002991E11530BAE14398A3E231D58C870F
#> 3 040000008200E00074C5B7101A82E00800000000A919FB2EF37FD401000000000000000010000000425B16930AE98845BC0A22AC5A61D045
#> 4 040000008200E00074C5B7101A82E00800000000116F453C2B5BD401000000000000000010000000C812F717C6F2E642A23B6EFB717946CD
#> 5 040000008200E00074C5B7101A82E00800000000F03F8842156AD401000000000000000010000000CAA7A28B3690964185045A8D2D80D513
#> 6 040000008200E00074C5B7101A82E0080000000004A85126F07FD4010000000000000000100000006EEE18C0FD2F40449282F0FCD595ACA7
#>                                                                                                                       summary
#> 1                                                                                           Meet-up re global health projects
#> 2                                                                                                R markup training with Robin
#> 3                                                                                           Send tweet re R workshop in Leeds
#> 4                                                                               CDAS cycling inequalities supervisory meeting
#> 5 ITS Research Seminar - Navigating Gender, Using Transportation: Theme and Variations in Urban India by Morgan Campbell, ITS
#> 6                                                         [Envnet] [Capemnet] Leeds Institute for Fluid Dynamics Open Meeting
#>                 start                 end
#> 1 2018-11-19 11:00:00 2018-11-19 11:30:00
#> 2 2018-11-20 09:00:00 2018-11-20 11:00:00
#> 3 2018-11-20 09:00:00 2018-11-20 09:30:00
#> 4 2018-11-20 15:00:00 2018-11-20 16:00:00
#> 5 2018-11-21 14:00:00 2018-11-21 15:00:00
#> 6 2018-11-21 14:00:00 2018-11-21 14:30:00
#>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            description
#> 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Heads-up: this will be a 3 way meeting now, to include Stephen Turrell from Leeds City Council, on the 9th floor of the Worsley Building.\n
#> 2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       COlin - Robin has agreed to do a training session for me and Roger on R Markup at this date and time if you want to join us.\n
#> 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   \n
#> 4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1 week before send review of lit review and we'll comment on it.\n
#> 5 Navigating Gender, Using Transportation: Theme and Variations in Urban India\n\nPresented by Morgan Campbell<https://environment.leeds.ac.uk/transport/staff/2569/morgan-campbell>, Institute for Transport Studies, University of Leeds.\n\nDate: Wednesday 21st November 2018\nTime: 14.00-15.00\nLocation: rm 1.11 Institute for Transport Studies<http://www.its.leeds.ac.uk/map/>, University of Leeds\nAll welcome. No booking required.\n\nAbstract\nStarting with the awareness of overt patriarchal structures and gender norms that affect when, where, and why women in urban India travel, this presentation focuses on how gender and class positions are moved and removed by available transport. The geographies of Bengaluru and Delhi were chosen for the significant physical and social transformations that reflect realities of globalization, conflicting political ideologies, internal migration, and rapid urbanization. These changes are embedded within slick metro systems, the millions of new car owners, company provided transportation for employees of multinationals, and failing public bus systems. They are transcribed onto the bodies of urban women in which a tension between mobility in a literal sense and immobility with respect to gender norms and socio-economic hierarchies constantly plays out.\n\nBio\nMorgan Campbell is an interdisciplinary researcher with a background in urban planning and gender studies. She has worked on issues related to urbanization, gender, and mobility in India for the past eight years.\n\nWatch recent ITS Research seminars:\nPlanning for sustainable and resilient cities: Improving decision-making through accessibility instruments<https://environment.leeds.ac.uk/transport/events/event/94/planning-for-sustainable-and-resilient-cities-improving-decision-making-through-accessibility-instruments> by Dr Benjamin Buttner, Technical University of Munich.\n"It's time" in Vancouver – Is equity the key to resolving the paradox of mobility pricing?<https://mymedia.leeds.ac.uk/Mediasite/Showcase/default/Presentation/825a83352f334051b6e05b8c47f7a3fc1d> by Dr Abraham Leung, Griffith University, Australia.\nExploring port and mode decisions for grain consolidators in Argentina. A behavioural model<https://mymedia.leeds.ac.uk/Mediasite/Showcase/default/Presentation/bba7e578bbe64299a0e84708275e58701d> by Rodrigo Tapia<https://www.its.leeds.ac.uk/people/r.tapia>, ITS, University of Leeds.\nAn introduction to Pedestrian in the Loop Simulation and the University of Leeds PEDSIM<http://www.its.leeds.ac.uk/fileadmin/documents/seminars/Romano_R_Abstract___Bio_01_03_2018.docx> by Professor Richard Romano, ITS, University of Leeds\n\nTo see more seminars like these, visit the ITS Events webpage: https://environment.leeds.ac.uk/events/6/transport\n\n\n
#> 6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                The meeting will take place on the 21st Nov 2-4pm, Parkinson SR B.08.
#>                                              location  class priority
#> 1                                           Pure cafe PUBLIC        5
#> 2 room 11.01 (small meeting room near LIDA reception) PUBLIC        5
#> 3                                                     PUBLIC        5
#> 4                                           ITS foyer PUBLIC        5
#> 5                                         ITS rm 1.11 PUBLIC        5
#> 6                                   Parkinson SR B.08 PUBLIC        5
#>        transp             dtstamp last_modified    status
#> 1      OPAQUE 2019-02-18 07:56:17          <NA> CONFIRMED
#> 2      OPAQUE 2019-02-18 07:56:17          <NA> CONFIRMED
#> 3      OPAQUE 2019-02-18 07:56:17          <NA> CONFIRMED
#> 4      OPAQUE 2019-02-18 07:56:17          <NA> CONFIRMED
#> 5 TRANSPARENT 2019-02-18 07:56:17          <NA> CONFIRMED
#> 6      OPAQUE 2019-02-18 07:56:17          <NA> CONFIRMED
```

<sup>Created on 2019-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
